x-ulimits: &default-ulimits
  ulimits:
    nofile:
      soft: 65536
      hard: 65536

services:
  nginx:
    image: openwisp-nginx:latest
    build:
      context: images
      dockerfile: openwisp_nginx/Dockerfile

  postgres_backup:
    image: prodrigestivill/postgres-backup-local
    restart: always # Ensure the backup container restarts if it crashes
    environment:
      POSTGRES_HOST: postgres # This MUST match the service name of your PostgreSQL container
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      SCHEDULE: "0 3 * * *" # Example: Run daily at 3 AM. Adjust as needed.
      BACKUP_KEEP_DAYS: 7    # Keep daily backups for 7 days
      BACKUP_KEEP_WEEKS: 4   # Keep weekly backups for 4 weeks (1 month)
      BACKUP_KEEP_MONTHS: 6  # Keep monthly backups for 6 months
      # Optional: set TZ for backup container to match your system/DB for consistent scheduling
      TZ: ${TZ} # Uncomment and ensure TZ is defined in your .env or similar
    <<: *default-ulimits
    cpus: "2.5"
    mem_limit: "2048M"
    volumes:
      - $HOME/openwisp/backups/postgres:/backups # Create a 'backups/postgres' folder on your host for backups
    depends_on:
      postgres:
        condition: service_healthy # Ensures the DB is healthy before attempting backup
                                   # Requires the postgres healthcheck above.

